### ISSUE TITLE
Heads Up 1.0.2a

### ISSUE THREAD

**Issue by splitice** [PeterMosmans/openssl#11]
Heads up. There are forthcoming security updates for OpenSSL today/tomorrow.
 
https://mta.openssl.org/pipermail/openssl-announce/2015-March/000020.html

**Comment by centminmod** [comment]
indeed @splitice :+1:

**Comment by PeterMosmans** [comment]
I'm watching the official repository closely. As one of OpenSSL's head honchos Matt Caswell stated yesterday (March 18th): 

>I have received a number of queries regarding the timing of Thursday's release.
>To clarify, we are aiming to have the release available sometime between 1100-1500 GMT.

I'm going to push the most recent merged patches now, and as soon as the vulnerability patches are out I'll merge, test and push them. To notify you I will keep this issue open until these patches are pushed.

**Comment by splitice** [comment]
Thanks for your hard work. I was not aware of the time of release and have noted it it myself.

**Comment by PeterMosmans** [comment]
Merged like a breeze, please enjoy release 95044c33d6c090f4970ed8e78172fbc0bf5e1451

Cheers,

Peter

**Comment by splitice** [comment]
Thank you for your continued hard work +1

**Comment by DomT4** [comment]
Awesome! Thanks Peter :+1:
