### ISSUE TITLE
Arm version does not compile

### ISSUE THREAD

**Issue by raybondo** [PeterMosmans/openssl#17]
https://github.com/PeterMosmans/openssl/blob/1.0.2-chacha/crypto/evp/e_aes.c#L1279
Line 1279 of crypto/evp/e_aes.c has unknown values as the first to arguments to the call to CRYPTO_gcm128_init.

**Comment by PeterMosmans** [comment]
Thanks for this bugreport as well @raybondo , and please let me know if this fix works on an ARM architecture. Personally I don't test on that environment (as you probably found out :) )

**Comment by raybondo** [comment]
Yep, it does work on the different Android ARM devices I've tested so far.
Thanks for the library and quick fixes.
