### ISSUE TITLE
Wrong configure line for mips64_asm

### ISSUE THREAD

**Issue by raybondo** [PeterMosmans/openssl#18]
The line for mips64_asm has an incorrect number of colons.
It is currently
my $mips64_asm=":bn-mips.o mips-mont.o::aes_cbc.o aes-mips.o:::sha1-mips.o sha256-mips.o sha512-mips.o::::::::::";

but should be
my $mips64_asm=":bn-mips.o mips-mont.o:::aes_cbc.o aes-mips.o:::sha1-mips.o sha256-mips.o sha512-mips.o::::::::::";

There's a missing colon between the mips-mont.o and aes_cbc.o.
This was causing the mips64 and 32 versions to fail to build.

**Comment by PeterMosmans** [comment]
Thanks for reporting this issue @raybondo, much appreciated. I found other discrepancies as well when running a fresh `make TABLE`. I'm working on it...
