### ISSUE TITLE
Build fails von ARMv7

### ISSUE THREAD

**Issue by f-s** [PeterMosmans/openssl#24]
Using your

<pre>
./config --prefix=/usr/ --openssldir=/etc/ssl enable-zlib enable-ssl2 enable-rc5 enable-rc2 \
enable-GOST enable-cms enable-md2 enable-mdc2 enable-ec enable-ec2m enable-ecdh enable-ecdsa \
enable-seed enable-camellia enable-idea enable-rfc3779 no-ec_nistp_64_gcc_128 \
-static experimental-jpake -DOPENSSL_USE_BUILD_DATE
</pre>

on Ubuntu 14.04 LTS (with libssl-dev, libsslcommon2-dev ), maybe we can get this working.

<pre>
e_aes.c: In function 'aes_gcm_set_key':
e_aes.c:1280:36: error: 'gctx' undeclared (first use in this function)
       CRYPTO_gcm128_init(gcm_ctx, &gctx->ks,
                                    ^
</pre>

I tried `no-evp` also fails, with `error: unknown type name 'EVP_CIPHER_INFO'` The original 1.1.x compiles fine from GIT.

Cheers

**Comment by PeterMosmans** [comment]
@f-s , thanks for your report. 
Which commit/branch are you using ? And which architecture (64 bit I presume) ?
The latest builds succeed on x86_64 platforms, see https://travis-ci.org/PeterMosmans/openssl
I'm going to look into it.

Cheers,

Peter

**Comment by teward** [comment]
@PeterMosmans Based on https://github.com/drwetter/testssl.sh/issues/129 my guess would be ARM.  And based on "on Ubuntu 14.04 LTS" I'm also assuming that they're either crosscompiling or compiling on armhf (the only truly supported ARM variant of Ubuntu right now, which is for the ARMv7 and up instruction sets)

**Comment by f-s** [comment]
@PeterMosmans @PeterMosmans I am using the `default` branch: `1.0.2-chacha` and I am doing a native armhf compile. Still issues are, as described in the first post. Thanks!

**Comment by PeterMosmans** [comment]
Thanks for letting me know. This issue was supposedly fixed in df1bc348616234df551585bf84ccaa522226e249 in May 5, 2015. I' ll create a special arm branch for you to test.

**Comment by PeterMosmans** [comment]
Could you try the arm branch ?
https://github.com/PeterMosmans/openssl/tree/arm

Thanks in advance,

Peter

**Comment by f-s** [comment]
Hello Peter,

the Patch works fine, thank you!

Best regards!

**Comment by drwetter** [comment]
@f-s If you like you can put the binary as PR into https://github.com/drwetter/testssl.sh/tree/master/bin . Naming scheme ist ```openssl.$(uname).$(uname -m)```.

**Comment by f-s** [comment]
@drwetter Hi, so I did.

**Comment by drwetter** [comment]
thx again!
