### ISSUE TITLE
Various errors on Win32 and Win64

### ISSUE THREAD

**Issue by nabla-c0d3** [PeterMosmans/openssl#37]
Hi,
I am using this OpenSSL fork compiled with VS 2009 in my own tool, and it is causing various errors (  https://github.com/nabla-c0d3/sslyze/issues/139, https://github.com/nabla-c0d3/sslyze/issues/129 ) that we are not getting with the official OpenSSL. Unfortunately I don't have time to troubleshoot these, but I would perhaps add a mention in the README that the fork does not work well as a replacement of OpenSSL when compiled with Visual Studio.
Thanks,

**Comment by PeterMosmans** [comment]
Thanks for reporting. Picking this up

**Comment by nabla-c0d3** [comment]
Closing this as it was due to something on my side. Sorry for the false report!
