### ISSUE TITLE
Compile failure with latest commits which restore EC curves, Ubuntu 14.04 x86_64

### ISSUE THREAD

**Issue by teward** [PeterMosmans/openssl#40]
Compile failure, Ubuntu 14.04 x86_64.  Tested the commits which you said would fix https://github.com/drwetter/testssl.sh/issues/299 and it fails to compile.

Using the instructions for compiling at https://github.com/drwetter/testssl.sh/blob/master/bin/Readme.md to get a reproducible build (with Kerberos) of the static-compiled versions from drwetter, because I like compiling stuff locally to avoid any odd issues.

This is where in the make output it triggers:

```
gcc -I../crypto -I.. -I../include -I/usr/kerberos/include -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DKRB5_MIT -DOPENSSL_USE_BUILD_DATE -Wa,--noexecstack -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_EXPERIMENTAL_JPAKE -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM   -c -o t1_lib.o t1_lib.c
t1_lib.c: In function 'tls1_shared_curve':
t1_lib.c:576:16: error: 'eccurves_all' undeclared (first use in this function)
         supp = eccurves_all;
                ^
t1_lib.c:576:16: note: each undeclared identifier is reported only once for each function it appears in
t1_lib.c: In function 'ssl_set_client_disabled':
t1_lib.c:1180:5: warning: implicit declaration of function 'kssl_tgt_is_available' [-Wimplicit-function-declaration]
     if (!kssl_tgt_is_available(s->kssl_ctx)) {
     ^
make[1]: *** [t1_lib.o] Error 1
make[1]: Leaving directory `/home/teward/openssl-1.0.2-fork/openssl-compile/ssl'
make: *** [build_ssl] Error 1
```

**Comment by teward** [comment]
This worked, I believe, before the latest set of commits for the ECDHE-RSA-RC4-SHA changes and the curves changes.

**Comment by PeterMosmans** [comment]
@teward , thanks for the headsup. ravis also warned me about broken builds. Please check the latest one, which should fix this. My bad - forgot to commit the complete file.

**Comment by teward** [comment]
@PeterMosmans I'll pull shortly, got to restart my DNS server which apparently hates me every fifty thousand requests, then I'll build.  This report made was more-or-less to link to the issue on drwetter's testssl.sh script, but also to make sure there's an issue made on this in case someone comes around wanting to report ;)  (Rapid-reporting has its advantages and disadvantages)

**Comment by teward** [comment]
@PeterMosmans Compile succeeded with the fix, apologies for being extremely rapid on reporting this, but since this was a blocking bug for testssl.sh's release, wanted to make sure it was reported.

Thanks again for a rapid fix!

**Comment by PeterMosmans** [comment]
No worries, I'd rather hear bugs twice than never :smile: Thank you for reporting.
