### ISSUE TITLE
"openssl speed chacha20-poly1305" gives empty result

### ISSUE THREAD

**Issue by eakraly** [PeterMosmans/openssl#6]
Looks like the code that should actually execute the speed test is missing.

**Comment by PeterMosmans** [comment]
Thanks for posting the bugreport. I'm going to look into it.

**Comment by PeterMosmans** [comment]
Fixed in https://github.com/PeterMosmans/openssl/commit/d7e8153a5593c90bf45777d185a380ad816fe7cb
Thanks once again for taking the time to post this bugreport!
