### ISSUE TITLE
Fails to build on Win32 using MSVC compiler

### ISSUE THREAD

**Issue by eakraly** [PeterMosmans/openssl#8]
The reason seams to be ssize_t used in files related to chacha20poly1305 and aead in general - ssize_t is not defined in MSVC (and is not a type defined in standard). I think following comment in CHANGES might be related to this:
  *) Use type ossl_ssize_t instad of ssize_t which isn't available on
     all platforms. Move ssize_t definition from e_os.h to the public
     header file e_os2.h as it now appears in public header file cms.h
     [Steve Henson]

**Comment by PeterMosmans** [comment]
Thanks for reporting this issue.
ssize_t is indeed a POSIX type definition and not pure C. Personally I'm using msys2/mingw most of the time when testing the build process on Windows, which 

Could you test the latest release (efe0953e9b55365a213227bf4b38084bda595c4d) ?

I'm working on a build - it would be great i

**Comment by eakraly** [comment]
There is one more related issue - SSIZE_MAX which is defined for ssize_t

**Comment by PeterMosmans** [comment]
Thanks for your feedback, commit abdfd1f251cb425093e337630fa2b19da5aa4900 should fix it.
I defined SSIZE_MAX as INT_MAX, which is way too low for a proper 64 architecture. If you look at the code however the values in size_t will be equal or lower, so I don't expect any issues there on MSVC.
